export enum Team {
  AL_AHLY = 'Al Ahly',
  ZAMALEK = 'Zamalek',
  PYRAMIDS = 'Pyramids',
  FUTURE = 'Future',
  AL_MASRY = 'Al Masry',
  ISMAILY = 'Ismaily',
  AL_ITTIHAD = 'Al Ittihad',
  AL_MOKAWLOON = 'Al Mokawloon',
  ZED = 'Zed',
  AL_GONA = 'Al Gona',
  BALADEYA = 'Baladeya',
  SMOHA = 'Smoha',
  CYRAMECAL_CLEOPATRA = 'Cyramecal Cleopatra',
  ENPY = 'Enpy',
  TALA3_EL_GAISH = 'Tala3 El Gaish',
  FARCO = 'Farco',
  ELDAKHLEYA = 'Eldakhleya',
  ELBANK_EL_AHLY = 'Elbank El Ahly',
}
